### PR TITLE
Resolve #1

### LINKED ISSUE #1: Too long sentence can't be processed due to the use of "spawn"
Since `cabocha.ts` use the method `child_process.spawn`, and tries to receive data generated by CaboCha in `p.on('data', (data) => ...)`, some long sentences can't be processed correctly.

Environment:
- macOS Catalina 10.15.2,
- Debian 9.11

<details>
<summary>Example sentence:</summary>
例えばこのような非常に冗長な文章を作る人がいる場合、その係り受け解析の結果を受け取るときに標準出力からチャンクごとにイベント形式でとるならば一つのチャンクに全ての結果が含まれないことがあるため、それを考慮した上でもう一度実装を確認しながら書き直すことにより正しく解析結果を受け渡すことが可能となるのですが、しかしながら環境によってはこれを行わなくても普通に全ての結果を受け取ってしまうことが可能なため、再現性がなかなかとれないのが難しいところではある中で、検証のためmacOS上でもこのような長い文章を解析させるような試みをしてみたところ、やはりこれが他環境と同様にうまく動かなくなってしまったため、私はこのようなテストを書くのがあまり得意ではないけれども書いてよかったなと感じた訳でございますが、せっかくなのでもう少しだけ長い文章を書きたいなと思っているのでたった今このような駄文を大量に生成している私がここに存在している次第でありました。
</details>

<details>
<summary>Output for the sentence above:</summary>

```
{
  depRels: [
    [ 41, '例えば', [Array] ],
    [ 2, 'このような', [Array] ],
    [ 3, '非常に', [Array] ],
    [ 4, '冗長な', [Array] ],
    [ 5, '文章を', [Array] ],
    [ 6, '作る', [Array] ],
    [ 7, '人が', [Array] ],
    [ 8, 'いる', [Array] ],
    [ 41, '場合、', [Array] ],
    [ 10, 'その', [Array] ],
    [ 11, '係り', [Array] ],
    [ 19, '受け', [Array] ],
    [ 13, '解析の', [Array] ],
    [ 14, '結果を', [Array] ],
    [ 15, '受け取る', [Array] ],
    [ 19, 'ときに', [Array] ],
    [ 19, '標準出力から', [Array] ],
    [ 19, 'チャンクごとに', [Array] ],
    [ 19, 'イベント形式で', [Array] ],
    [ 24, 'とるならば', [Array] ],
    [ 21, '一つの', [Array] ],
    [ 24, 'チャンクに', [Array] ],
    [ 23, '全ての', [Array] ],
    [ 24, '結果が', [Array] ],
    [ 25, '含まれない', [Array] ],
    [ 26, 'ことが', [Array] ],
    [ 27, 'ある', [Array] ],
    [ 41, 'ため、', [Array] ],
    [ 29, 'それを', [Array] ],
    [ 30, '考慮した', [Array] ],
    [ 33, '上で', [Array] ],
    [ 33, 'もう一度', [Array] ],
    [ 33, '実装を', [Array] ],
    [ 34, '確認しながら', [Array] ],
    [ 35, '書き直す', [Array] ],
    [ 38, 'ことにより', [Array] ],
    [ 38, '正しく', [Array] ],
    [ 38, '解析結果を', [Array] ],
    [ 39, '受け渡す', [Array] ],
    [ 40, 'ことが', [Array] ],
    [ 41, '可能と', [Array] ],
    [ 101, 'なるのですが、', [Array] ],
    [ 49, 'しかしながら', [Array] ],
    [ 45, '環境によっては', [Array] ],
    [ 45, 'これを', [Array] ],
    [ 49, '行わなくても', [Array] ],
    [ 49, '普通に', [Array] ],
    [ 48, '全ての', [Array] ],
    [ 49, '結果を', [Array] ],
    [ 50, '受け取ってしまう', [Array] ],
    [ 51, 'ことが', [Array] ],
    [ 52, '可能な', [Array] ],
    [ 55, 'ため、', [Array] ],
    [ 55, '再現性が', [Array] ],
    [ 55, 'なかなか', [Array] ] // truncated
  ],
```

</details>

### PR DESCRIPTION
**Pull request by private-yusuke**

### CODE REVIEW

**Comment by hikalium** [comment]
Thank you for the p-r!
Unfortunately, I have no time to review this p-r until February, so please wait for a while.
Sorry and thank you for the patience!

**Comment by hikalium** [comment]
LGTM. Thanks for your contribution and patience!

**Comment by private-yusuke** [comment]
I wish if you release this change as version 0.0.5 so that I can use this package for my product.

**Comment by hikalium** [comment]
Published as 0.0.5. Thanks!
https://www.npmjs.com/package/node-cabocha/v/0.0.5

**Pull request merged**
